// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsvqutkccemkxclodeyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzdnF1dGtjY2Vta3hjbG9kZXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTE5NjAsImV4cCI6MjA3MzYyNzk2MH0.UyK-rK-y4_Vor9FuaVHuUee7fnDoXptLcCLNwKE94bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});